//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Advertisement
    {
        public int Id { get; set; }

        [DisplayName("Tiêu đề")]
        [Required(ErrorMessage = "Vui lòng nhập tiêu đề")]
        [StringLength(100, ErrorMessage = "Độ dài không được vượt quá 100 ký tự")]
        public string Title { get; set; }

        [DisplayName("Ảnh")]
        [Required(ErrorMessage = "Ảnh không được để trống")]
        public string ImageUrl { get; set; }

        [DisplayName("Link")]
        [Required(ErrorMessage = "Link không được để trống")]
        public string TargetUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }

        [DisplayName("Ngày hết hạn")]
        [Required(ErrorMessage = "Vui lòng nhập ngày hết hạn")]
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
