//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public System.Guid Id { get; set; }

        [DisplayName("Nội dung")]
        [Required(ErrorMessage = "Nội dung không được để trống")]
        [StringLength(100, ErrorMessage = "Độ dài không được vượt quá 100 ký tự")]
        public string Content { get; set; }
        public System.Guid AuthorId { get; set; }
        public System.Guid ArticleId { get; set; }
        public System.DateTime PublishDate { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual USER USER { get; set; }
    }
}
