//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.Articles = new HashSet<Article>();
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ Email")]
        [DisplayName("Địa chỉ Email")]
        [EmailAddress(ErrorMessage = "Địa chỉ Email không hợp lệ")]
        [StringLength(50, ErrorMessage = "Độ dài không được vượt quá 50 ký tự")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu!")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,}$",
        ErrorMessage = "Mật khẩu phải dài ít nhất 8 ký tự và chứa ít nhất một chữ hoa, một chữ thường và một chữ số  và một ký tự đặt biệt")]
        [DisplayName("Mật khẩu")]
        [StringLength(50, ErrorMessage = "Độ dài không được vượt quá 50 ký tự")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nhập lại mật khẩu!")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Mật khẩu và mật khẩu xác nhận không khớp")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPassword { get; set; }

        [DisplayName("Tên hiển thị")]
        [StringLength(50, ErrorMessage = "Độ dài không được vượt quá 50 ký tự")]
        public string DisplayName { get; set; }

        [DisplayName("Ngày tham gia")]
        public System.DateTime JoinDate { get; set; }

        [DisplayName("Ảnh đại diện")]
        public string Avatar { get; set; }

        [DisplayName("Quyền")]
        public string Role { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
